apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-postgres
spec:
  capacity:
    storage: 20Gi
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: immich
    name: immich-postgres
  hostPath:
    path: /opt/immich/postgres
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: ["pc2"]
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library
spec:
  capacity:
    storage: 1000Gi
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: immich
    name: immich-library
  hostPath:
    path: /opt/immich/library
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: ["pc2"]
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-model-cache
spec:
  capacity:
    storage: 10Gi
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: immich
    name: immich-model-cache
  hostPath:
    path: /opt/immich/model-cache
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: ["pc2"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgres
  namespace: immich
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: ""
  volumeName: immich-postgres
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: ""
  volumeName: immich-library
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-model-cache
  namespace: immich
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: ""
  volumeName: immich-model-cache
  resources:
    requests:
      storage: 10Gi
